export const payloadBranch = {
  branch1: {
    branchName: `Branch Djakarta AT-RHAMA`,
    streetAddress: "Address Testing",
    province: "DKI JAKARTA",
    city: "JAKARTA SELATAN",
    district: "PESANGGRAHAN",
    subdistrict: "BINTARO",
    postalCode: "12330",
  },
  branch2: {
    branchName: `Branch Bandung AT-RHAMA`,
    streetAddress: "Address Testing",
    province: "DKI JAKARTA",
    city: "JAKARTA SELATAN",
    district: "PESANGGRAHAN",
    subdistrict: "BINTARO",
    postalCode: "12330",
  },
  branch3: {
    branchName: `Branch Jogja AT-RHAMA`,
    streetAddress: "Address Testing",
    province: "DKI JAKARTA",
    city: "JAKARTA SELATAN",
    district: "PESANGGRAHAN",
    subdistrict: "BINTARO",
    postalCode: "12330",
  },
  branch4: {
    branchName: `Branch Semarang AT-RHAMA`,
    streetAddress: "Address Testing",
    province: "DKI JAKARTA",
    city: "JAKARTA SELATAN",
    district: "PESANGGRAHAN",
    subdistrict: "BINTARO",
    postalCode: "12330",
  },
  branch5: {
    branchName: `Branch Surabaya AT-RHAMA`,
    streetAddress: "Address Testing",
    province: "DKI JAKARTA",
    city: "JAKARTA SELATAN",
    district: "PESANGGRAHAN",
    subdistrict: "BINTARO",
    postalCode: "12330",
  },
};

export const payloadCustomers = {
  customers1: {
    customerName: `Customer ${payloadBranch.branch1.branchName}`,
  },
  customers2: {
    customerName: `Customer ${payloadBranch.branch2.branchName}`,
  },
  customers3: {
    customerName: `Customer ${payloadBranch.branch3.branchName}`,
  },
  customers4: {
    customerName: `Customer ${payloadBranch.branch4.branchName}`,
  },
  customers5: {
    customerName: `Customer ${payloadBranch.branch5.branchName}`,
  },
};

export const payloadWarehouse = {
  warehouse1: {
    warehouseName: `Warehouse ${payloadBranch.branch1.branchName}`,
    shortName: `WH${payloadBranch.branch1.branchName}`,
    ownerType: "Company",
    branch: payloadBranch.branch1.branchName,
    warehouseNameEdit: "Warehouse 26 Oktober Edit",
    shortNameEdit: "WH26OKTEDIT",
  },
  warehouse2: {
    warehouseName: `Warehouse ${payloadBranch.branch2.branchName}`,
    shortName: `WH${payloadBranch.branch2.branchName}`,
    ownerType: "Company",
    branch: payloadBranch.branch2.branchName,
    warehouseNameEdit: "Warehouse 26 Oktober Edit",
    shortNameEdit: "WH26OKTEDIT",
  },
  warehouse3: {
    warehouseName: `Warehouse ${payloadBranch.branch3.branchName}`,
    shortName: `WH${payloadBranch.branch3.branchName}`,
    ownerType: "Company",
    branch: payloadBranch.branch3.branchName,
    warehouseNameEdit: "Warehouse 26 Oktober Edit",
    shortNameEdit: "WH26OKTEDIT",
  },
  warehouse4: {
    warehouseName: `Warehouse ${payloadBranch.branch4.branchName}`,
    shortName: `WH${payloadBranch.branch4.branchName}`,
    ownerType: "Company",
    branch: payloadBranch.branch4.branchName,
    warehouseNameEdit: "Warehouse 26 Oktober Edit",
    shortNameEdit: "WH26OKTEDIT",
  },
  warehouse5: {
    warehouseName: `Warehouse ${payloadBranch.branch5.branchName}`,
    shortName: `WH${payloadBranch.branch5.branchName}`,
    ownerType: "Company",
    branch: payloadBranch.branch5.branchName,
    warehouseNameEdit: "Warehouse 26 Oktober Edit",
    shortNameEdit: "WH26OKTEDIT",
  },
};

export const payloadProduct = {
  product1: {
    productName: "Kaos AT-Rhama",
    productType: "All",
    cost: "10000",
    basePrice: "30000",
    category: "All",
    baseUom: "Units",
    level1: "Small",
    level2: "Medium",
    uomLevel2: "Dozens",
    convertionLevel2: "12",
    extraPrice1: "3000",
    extraPrice2: "5000",
    extraPrice3: "7000",
  },
  product2: {
    productName: "Celana AT-Rhama",
    productType: "All",
    cost: "10000",
    basePrice: "40000",
    category: "All",
    baseUom: "Units",
    level1: "Small",
    level2: "Medium",
    uomLevel2: "Dozens",
    convertionLevel2: "12",
    extraPrice1: "3000",
    extraPrice2: "5000",
    extraPrice3: "7000",
  },
  product3: {
    productName: "Topi AT-Rhama",
    productType: "All",
    cost: "10000",
    basePrice: "50000",
    category: "All",
    baseUom: "Units",
    level1: "Small",
    level2: "Medium",
    uomLevel2: "Dozens",
    convertionLevel2: "12",
    extraPrice1: "3000",
    extraPrice2: "5000",
    extraPrice3: "7000",
  },
  product4: {
    productName: "Jaket AT-Rhama",
    productType: "All",
    cost: "10000",
    basePrice: "60000",
    category: "All",
    baseUom: "Units",
    level1: "Small",
    level2: "Medium",
    uomLevel2: "Dozens",
    convertionLevel2: "12",
    extraPrice1: "3000",
    extraPrice2: "5000",
    extraPrice3: "7000",
  },
  product5: {
    productName: "Sweater AT-Rhama",
    productType: "All",
    cost: "10000",
    basePrice: "70000",
    category: "All",
    baseUom: "Units",
    level1: "Small",
    level2: "Medium",
    uomLevel2: "Dozens",
    convertionLevel2: "12",
    extraPrice1: "3000",
    extraPrice2: "5000",
    extraPrice3: "7000",
  },
  product6: {
    productName: "Gesper AT-Rhama",
    productType: "All",
    cost: "10000",
    basePrice: "80000",
    category: "All",
    baseUom: "Units",
    level1: "Small",
    level2: "Medium",
    uomLevel2: "Dozens",
    convertionLevel2: "12",
    extraPrice1: "3000",
    extraPrice2: "5000",
    extraPrice3: "7000",
  },
  product7: {
    productName: "Dasi AT-Rhama",
    productType: "All",
    cost: "10000",
    basePrice: "80000",
    category: "All",
    baseUom: "Units",
    level1: "Small",
    level2: "Medium",
    uomLevel2: "Dozens",
    convertionLevel2: "12",
    extraPrice1: "3000",
    extraPrice2: "5000",
    extraPrice3: "7000",
  },
  product8: {
    productName: "Jam Tangan AT-Rhama",
    productType: "All",
    cost: "10000",
    basePrice: "90000",
    category: "All",
    baseUom: "Units",
    level1: "Small",
    level2: "Medium",
    uomLevel2: "Dozens",
    convertionLevel2: "12",
    extraPrice1: "3000",
    extraPrice2: "5000",
    extraPrice3: "7000",
  },
  product9: {
    productName: "Kacamata AT-Rhama",
    productType: "All",
    cost: "10000",
    basePrice: "100000",
    category: "All",
    baseUom: "Units",
    level1: "Small",
    level2: "Medium",
    uomLevel2: "Dozens",
    convertionLevel2: "12",
    extraPrice1: "3000",
    extraPrice2: "5000",
    extraPrice3: "7000",
  },
  product10: {
    productName: "Sepatu AT-Rhama",
    productType: "All",
    cost: "10000",
    basePrice: "100000",
    category: "All",
    baseUom: "Units",
    level1: "Small",
    level2: "Medium",
    uomLevel2: "Dozens",
    convertionLevel2: "12",
    extraPrice1: "3000",
    extraPrice2: "5000",
    extraPrice3: "7000",
  },
};

export const payloadStockAdjustment = {
  stock1: {
    product: `${payloadProduct.product1.productName}`,
    quantity: "8888",
    warehouse: `${payloadWarehouse.warehouse1.warehouseName}`,
  },
  stock2: {
    product: `${payloadProduct.product2.productName}`,
    quantity: "8888",
    warehouse: `${payloadWarehouse.warehouse1.warehouseName}`,
  },
  stock3: {
    product: `${payloadProduct.product3.productName}`,
    quantity: "8888",
    warehouse: `${payloadWarehouse.warehouse1.warehouseName}`,
  },
  stock4: {
    product: `${payloadProduct.product4.productName}`,
    quantity: "8888",
    warehouse: `${payloadWarehouse.warehouse1.warehouseName}`,
  },
  stock5: {
    product: `${payloadProduct.product5.productName}`,
    quantity: "8888",
    warehouse: `${payloadWarehouse.warehouse1.warehouseName}`,
  },
  stock6: {
    product: `${payloadProduct.product6.productName}`,
    quantity: "8888",
    warehouse: `${payloadWarehouse.warehouse1.warehouseName}`,
  },
  stock7: {
    product: `${payloadProduct.product7.productName}`,
    quantity: "8888",
    warehouse: `${payloadWarehouse.warehouse1.warehouseName}`,
  },
  stock8: {
    product: `${payloadProduct.product8.productName}`,
    quantity: "8888",
    warehouse: `${payloadWarehouse.warehouse1.warehouseName}`,
  },
  stock9: {
    product: `${payloadProduct.product9.productName}`,
    quantity: "8888",
    warehouse: `${payloadWarehouse.warehouse1.warehouseName}`,
  },
  stock10: {
    product: `${payloadProduct.product10.productName}`,
    quantity: "8888",
    warehouse: `${payloadWarehouse.warehouse1.warehouseName}`,
  },
};

export const payloadGoodReceipt = {
  receiveFrom: `${payloadCustomers.customers1.customerName}`,
  scheduleDate: "28",
  locationDestination: `${payloadWarehouse.warehouse1.warehouseName}`,
  product1: payloadProduct.product1.productName,
  demand1: "1000",
  product2: payloadProduct.product2.productName,
  demand2: "1000",
  product3: payloadProduct.product3.productName,
  demand3: "1000",
  product4: payloadProduct.product4.productName,
  demand4: "1000",
  product5: payloadProduct.product5.productName,
  demand5: "1000",
  product6: payloadProduct.product6.productName,
  demand6: "1000",
  product7: payloadProduct.product7.productName,
  demand7: "1000",
  product8: payloadProduct.product8.productName,
  demand8: "1000",
  product9: payloadProduct.product9.productName,
  demand9: "1000",
  product10: payloadProduct.product10.productName,
  demand10: "1000",
};

export const payloadDeliveries = {
  deliveryTo: `${payloadCustomers.customers1.customerName}`,
  scheduleDate: `28`,
  sourceLocation: `${payloadWarehouse.warehouse1.warehouseName}`,
  product1: `${payloadProduct.product1.productName}`,
  product2: `${payloadProduct.product2.productName}`,
  product3: `${payloadProduct.product3.productName}`,
  product4: `${payloadProduct.product4.productName}`,
  product5: `${payloadProduct.product5.productName}`,
  product6: `${payloadProduct.product6.productName}`,
  product7: `${payloadProduct.product7.productName}`,
  demand: `20`,
  uom: "Units",
  quantity: `20`,
};
